version: '3.0'
services:
  elasticsearch:
    container_name: es-container-t
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - xpack.security.enabled=false
      - 'discovery.type=single-node'
    networks:
      - es-net
    ports:
      - 9200:9200
    mem_limit: 3g
    cpus: 0.5
  kibana:
    container_name: kb-container-t
    image: docker.elastic.co/kibana/kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container-t:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  es-net:
    driver: bridge
